# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 15:12
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('nouvelles', '0003_allows_draft_articles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True,
                                              related_name='profile', serialize=False,
                                              to=settings.AUTH_USER_MODEL)),
                ('avatar', models.ImageField(upload_to='avatars/', null=True, blank=True)),
            ],
        ),
    ]
